version: '3.8'
services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: mocho
      MONGO_INITDB_ROOT_PASSWORD: mocho
    volumes:
      - mocho_data:/data/db

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: unless-stopped
    depends_on:
      - mongo
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mocho
      ME_CONFIG_MONGODB_ADMINPASSWORD: mocho
      ME_CONFIG_MONGODB_SERVER: 'mongo'

volumes:
  mocho_data:
